### ISSUE TITLE
Creating users - VF installer

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#10]
Trying the [test for phone hashing](https://learningequality.slack.com/archives/C0LE9NLCE/p1494432720892344) @jamalex recommended, on the VF installer we sent yesterday.

First problem is that I cannot login with the learner users I created previously as device owner:

![virtualbox_windows 7_11_05_2017_11_03_11](https://cloud.githubusercontent.com/assets/1457929/25942300/c786a0ec-363c-11e7-8716-f1a108d1a1a6.png)

I login as device owner then, change the password for that learner, try to login again, no luck. When user is created from the device owner **Manage users**, there's no field for phone number, so when I'm logging in as learner, I input the username in the **Phone number** field.  

But since this is VFs special setup for mobile phone users, so device owner is not supposed to create learners, right? So I try to **create a new account** and get the following error:
 
![virtualbox_windows 7_11_05_2017_11_10_01](https://cloud.githubusercontent.com/assets/1457929/25943038/de53300e-363e-11e7-9554-d01a420116dd.png)

I tried 7-11 digits for phone numbers, just in case, no luck. Is this the way users are supposed to create their own accounts?

When I check the `facilityuser` table, I only see the two users I created while logged in as device owner, so no way to check the phone hashing:

![virtualbox_windows 7_11_05_2017_11_30_23](https://cloud.githubusercontent.com/assets/1457929/25943108/0eed7c88-363f-11e7-92a9-881c039b28b6.png)

I realize now that I haven't played with creating users on VF installers before as much as I should have, but something is fishy here... 😞

**Comment by jamalex** [comment]
We don't expect users to be created by admins/DeviceOwners, yeah.

The signup issue looks like the issue we were getting where the default user plugin was not disabled.

**Comment by radinamatic** [comment]
@mrpau-eduard @mrpau-richard 

 I just tested @jamalex suggestion, run the command `kolibri plugin kolibri.plugins.user disable`, the error is gone, and phone hashing works (the first user in the table below was created by device owner, so it doesn't count :wink:):

![virtualbox_ie11 - win7_11_05_2017_17_09_15](https://cloud.githubusercontent.com/assets/1457929/25957307/d904daf6-3622-11e7-8f56-975681448890.png)

Can you please make sure the user gets properly disabled during install and build a new installer? Thanks!

**Comment by mrpau-eduard** [comment]
Hi @radinamatic we will implement this request today will sending a new set of installer.

**Comment by mrpau-richard** [comment]
Hi @radinamatic can you test the fix on this issue, using this [kolibri windows installer.]( https://buildkite.com/organizations/learningequality/pipelines/mrpau-vf-branded/builds/38/jobs/537a4040-d4df-4c61-9b72-4676bde264d4/artifacts/a3735d6b-27f8-4583-abf1-81227a2a5c10)

**Comment by radinamatic** [comment]
Just tested again, we should be good to go! :+1: 

![virtualbox_ie11 - win7_12_05_2017_06_56_35](https://cloud.githubusercontent.com/assets/1457929/25983032/f52078de-36e1-11e7-99be-7e94fe824c99.png)

**Comment by radinamatic** [comment]
![virtualbox_ie11 - win7_12_05_2017_07_11_07](https://cloud.githubusercontent.com/assets/1457929/25983118/87a183d8-36e2-11e7-8509-f9e37450c3e2.png)

**Comment by radinamatic** [comment]
Non extant on latest builds, closing!
