### ISSUE TITLE
Kolibri windows installer "Could not call proc"

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#11]
This issue will be reproduced when there's an existing KA Lite installed in the same machine during the installation of Kolibri windows installer.
![screen shot 2017-05-12 at 7 41 53 pm](https://cloud.githubusercontent.com/assets/8663934/25996679/15e96cb0-374b-11e7-8e0d-7a17120bddd1.png)

**Comment by mrpau-eduard** [comment]
Closing this issue already fix in #12

**Comment by radinamatic** [comment]
Good work, guys! 👍
