### ISSUE TITLE
Greek language is corrupted

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri-installer-windows#131]
When I install the Kolibri at Windows 7 and set the Language into Greek, the display is corrupted.

Refference : #125
![image](https://user-images.githubusercontent.com/38421180/62843656-0bef9600-bcee-11e9-99bb-103d1601df47.png)

**Comment by cpauya** [comment]
Glad that you spotted this issue.  

Please comment how you detected the issue and the tools/software you used so we can document it and hopefully prevent such issue from happening in the future.

I hope somebody who knows Greek can help us verify. 😺

**Comment by cpauya** [comment]
Also is this affected by this [previous commit (the link is a diff)](https://github.com/learningequality/kolibri-installer-windows/commit/d6129f85e841d02808f334b89bfda9cf63e29c9e#diff-227e84e45ddeeb4c7c7777fc715f367d)?

**Comment by mrpau-julius** [comment]
> Was wondering if this was affected by this previous commit (the link is a diff)?

@cpauya yes it is. Because in previous I'm using VS Code and add some changes string. I've not expected the UTF-8 in VS Code has an issue and not aware of that.
