### ISSUE TITLE
v0.13.0-beta1 installer on Windows not working

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#143]
Download from:
https://github.com/learningequality/kolibri/releases/tag/v0.13.0-beta1

Tested on Windows 7 VM:

- when trying to upgrade from 0.10, no errors reported during the installation, and 0.10 keeps loading:
   
   ![windows-not-updating](https://user-images.githubusercontent.com/1457929/69384605-00ccde80-0cbd-11ea-85a0-da774fe26b26.gif)

- when trying a fresh install, error alert appears, but not only there's no log file, there's not even a `.kolibri` home folder :confused: 

   ![windows-not-installing](https://user-images.githubusercontent.com/1457929/69384659-2ce85f80-0cbd-11ea-896d-6625d784070b.gif)

@jayoshih reported the [similar error during the hacksession](https://www.notion.so/learningequality/Error-installing-latest-version-on-Windows-bf7b48105695437890fe6fb3debbbdf3).

**Comment by mrpau-richard** [comment]
The cause of this issue is that the v0.13.0-beta1 `whl` has an error during the pip installation.
```
C:\Python34\Scripts>pip install C:\Users\MrPau\Downloads\kolibri-0.13.0b1-py2.py3-none-any.whl
You are using pip version 6.0.8, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing c:\users\mrpau\downloads\kolibri-0.13.0b1-py2.py3-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "C:\Python34\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "C:\Python34\lib\site-packages\pip\commands\install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "C:\Python34\lib\site-packages\pip\download.py", line 769, in unpack_url
      unpack_file_url(link, location, download_dir)
    File "C:\Python34\lib\site-packages\pip\download.py", line 717, in unpack_file_url
      unpack_file(from_path, location, content_type, link)
    File "C:\Python34\lib\site-packages\pip\utils\__init__.py", line 648, in unpack_file
      flatten=not filename.endswith('.whl')
    File "C:\Python34\lib\site-packages\pip\utils\__init__.py", line 544, in unzip_file
      fp = open(fn, 'wb')
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MrPau\\AppData\\Local\\Temp\\pip-build-xdo4xxb_\\kolibri\\kolibri/dist/kolibri_exercise_perseus_plugin/static/kolibri_exercise_perseus_plugin.exercise_perseus_render_module/kolibri_exercise_perseus_plugin.exercise_perseus_render_module-extra-widgets-1.2.2a3.js'
```
This error can only reproduce in Windows environment.

**Comment by indirectlylit** [comment]
@rtibbles any insight on why this might be happening?

` FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MrPau\\AppData\\Local\\Temp\\pip-build-xdo4xxb_\\kolibri\\kolibri/dist/kolibri_exercise_perseus_plugin/static/kolibri_exercise_perseus_plugin.exercise_perseus_render_module/kolibri_exercise_perseus_plugin.exercise_perseus_render_module-extra-widgets-1.2.2a3.js'`

**Comment by benjaoming** [comment]
The `\\` mixed with `/` is a bit suspicious... when do you get this error?

And do you find this file on the disk -- and if so: where?

**Comment by rtibbles** [comment]
It looks like this is the whl file being unpacked to a temporary location before install, right? But yes, the mixture of Windows and non-windows path separators is highly suspicious.

**Comment by radinamatic** [comment]
@mrpau-richard @mrpau-julius Shouldn't the log files related to errors during the installation on Windows be saved on the Desktop? In the case above it indicates the home folder, but that one is not even created during install.

**Comment by rtibbles** [comment]
I suspected that the additional `.` in file and folder names might be the cause of this, but from testing it does not appear to be.

**Comment by rtibbles** [comment]
*sigh* This appears to be a filename length issue.

**Comment by rtibbles** [comment]
Or, rather, a total filepath length?

**Comment by kollivier** [comment]
Ah, yup, limit is 255 chars. Looks like you can turn the limit off in newer Windows, but I suspect for the whl itself we should probably find ways to just reduce the total path length. :/

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation

**Comment by rtibbles** [comment]
We appear to have hit this issue: https://github.com/pypa/pip/issues/3055

**Comment by rtibbles** [comment]
Have worked around this locally by setting a much shorter temporary directory path before executing the pip install step. Will submit a PR to do this during our installation.

**Comment by rtibbles** [comment]
OK - actually not entirely sure how to handle this from Inno Setup Scripts - if it was a batch file, I would use:
```
setlocal %TMP%=%HOMEDRIVE%:\\temp
setlocal %TEMP%=%HOMEDRIVE%:\\temp
pip install <whl_file>
```

@mrpau-richard any ideas how to temporarily set the `TMP/TEMP` environment variables just while we're installing the whl file? The above batch script uses `setlocal` which just sets the variable for the purposes of the batch file but gets reset after.

**Comment by rtibbles** [comment]
The alternative solution is probably a bit simpler - simply shortening the file names with this PR: https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/209

@indirectlylit this would change translation file names.

**Comment by kollivier** [comment]
@rtibbles It also solves the problem for anyone using the whl file on Windows, not just the Windows installer, so I would vote for the rename!

**Comment by mrpau-richard** [comment]
> @mrpau-richard any ideas how to temporarily set the TMP/TEMP environment variables just while we're installing the whl file? The above batch script uses setlocal which just sets the variable for the purposes of the batch file but gets reset after.

I created a [PR](https://github.com/learningequality/kolibri-installer-windows/pull/144) for this @rtibbles , I used this command `set TEMP=HOMEDRIVE` to set temporary variable during the whi file installation only.

**Comment by indirectlylit** [comment]
created a `v1.3.5-beta1` tag and a v1.3.5 milestone:

* https://github.com/learningequality/kolibri-installer-windows/releases/tag/v1.3.5-beta1
* https://github.com/learningequality/kolibri-installer-windows/milestone/11


Updated PR to point at beta1 tag:

https://github.com/learningequality/kolibri/pull/6136
