### ISSUE TITLE
finalize windows installer v1.3.5

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#145]
steps:

1. Integrate the [latest translations from crowdin](https://crowdin.com/project/kolibri-windows-app/settings) into `develop`
2. Merge `develop` to `master`
3. Release 1.3.5 as [described in the readme](https://github.com/learningequality/kolibri-installer-windows#steps-for-making-windows-installer-releases)
4. Close the [1.3.5 milestone](https://github.com/learningequality/kolibri-installer-windows/milestones) and create a new 1.3.6 milestone
5. Celebrate!

**Comment by indirectlylit** [comment]
As far as I can tell, the changes from `develop` were never merged to `master` before tagging the release:

![image](https://user-images.githubusercontent.com/2367265/71189793-3cb18000-2238-11ea-9bfe-ba365cf75b1b.png)

**Comment by indirectlylit** [comment]
okay, I merged develop to master, deleted the existing tag, and re-tagged.

You may need to delete your local tag to properly update

![image](https://user-images.githubusercontent.com/2367265/71190905-3d4b1600-223a-11ea-9d78-5e211659a4d9.png)

**Comment by mrpau-richard** [comment]
> As far as I can tell, the changes from develop were never merged to master before tagging the release
 
This is my fault, I thought I pushed it to LE GIthub repo but it was only in `mrpau` I did not double check it before creating a release.

**Comment by indirectlylit** [comment]
no harm done!
