### ISSUE TITLE
error message refers to non-existent file

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#151]
The message refers to `kolibri.log`:

![image](https://user-images.githubusercontent.com/2367265/73556009-795dc300-4403-11ea-9ae6-9054e5dc6526.png)

However the files changed somewhat recently to `kolibri.txt` and `debug.txt` as described here:

https://kolibri.readthedocs.io/en/latest/manage/get_support.html#locate-kolibri-log-files

Let's update the ~docs~ modal to reflect the new log files.

**Comment by benjaoming** [comment]
> Let's update the docs

Shouldn't it be the Windows alert window that gets an update?

**Comment by indirectlylit** [comment]
yes sorry - that was a typo
