### ISSUE TITLE
Kolibri Installer failed to install

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#154]
During the Windows installation there is a possibility that the `pip.exe` did not install in Python or it was deleted by an antivirus. To fix this validate the `pip.exe` path if it exist before installing the Kolibri.

The  deleted `pip.exe` will not reinstall at the old Python34 path installation, unless manually uninstall the Python34 at the control panel  and delete the `C:\Python34'(if this folder is still exist). before installing the Python34 again.

**Comment by benjaoming** [comment]
Great observation @mrpau-richard -- just want to understand clearly: It means that `pip.exe` is copied into its location unconditionally (regardless of whether it already exists) by the Kolibri installer? And that this mechanism can trigger an antivirus program to detect and delete it?

**Comment by benjaoming** [comment]
Sorry nevermind, I didn't see there had been a conversation about it on Slack. Seems like we have had similar issues with `python.exe`

https://kolibri.readthedocs.io/en/latest/manage/get_support.html#antivirus
