### ISSUE TITLE
Mixed experience for KOLIBRI_SCRIPT_DIR addition to Path variable

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-installer-windows#161]
**Test Environments:**

I have executed this test on at least two Windows 10 systems.

1. System 1 - Kolibri has been upgraded on this system all the way to 0.13.2. It had Kolibri installed  even prior to 0.12.6 i.e. before the Windows installer enhancement of #102 was released.
2. System 2- Just installed Kolibri 0.13.2 for the first time on this.

**Experiences:**

System 1 - `kolibri manage` command would not run from a command window. 
Checked environment variables and found `KOLIBRI_SCRIPT_DIR` already set but not added to either Path in User variables nor in System variables. Neither had `C:\Python34\Scripts` as well.
Manually added `%KOLIBRI_SCRIPT_DIR%` to the System's `Path` variable to get the `kolibri` command working.

System 2 - User's `Path` variable had `C:\Python34\Scripts` prepended right upon installation of 0.13.2. So `kolibri manage` executed without any issues.

**Observation and Suggestion:**

1. I suspect for some logical reason/error when upgrading on systems installed prior to Kolibri 0.12.6/7, the `Path` variable does not get prepended. I don't have any other Python installed on these test systems. However, I may have uninstalled and reinstalled Kolibri on System 1 in the past.
2. Since `KOLIBRI_SCRIPT_DIR` system variable is being set, it should be used as `%KOLIBRI_SCRIPT_DIR%` to prepend to the `Path` variable (User or System variables) to ensure a single source of truth. May also be helpful in all cases wherein the Path variable needs to be checked. Once case that I can think of is clean-up during uninstallation.
3. Should the variable be prepended to the User's or System's `Path` variable? I think System variable.

*References:*
[Import multiple users from CSV](https://community.learningequality.org/t/import-multiple-users-from-csv/1264/11)
https://github.com/learningequality/kolibri-installer-windows/issues/102
https://github.com/learningequality/kolibri-installer-windows/pull/107
https://github.com/learningequality/kolibri-docs/issues/107

**Comment by cpauya** [comment]
Thanks for reporting this - we will look into it.

**Comment by mrpau-richard** [comment]
I successfully reproduced this issue and I will work on it. Thanks for reporting this @intelliant01
