### ISSUE TITLE
ExtractTemporaryFile: The file "python-3.6.8-amd64.exe" was not found

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#171]
[New Windows installer](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1130/jobs/0bb4c2b3-603e-47eb-9235-eddcfd2a3938/artifacts/11fa981b-e061-49cc-98bc-190f268a1f1b) with Python 3.6 not working :confused: 

### Windows 7
![Win7 (new start)  Running  - Oracle VM VirtualBox_587](https://user-images.githubusercontent.com/1457929/84856488-22c9ec00-b067-11ea-984a-b17f82c75f95.png)

[Kolibri-setup-W7.log](https://github.com/learningequality/kolibri-installer-windows/files/4790419/Kolibri-setup-W7.log)

### Windows 10
![Win10 (ITA)  Running  - Oracle VM VirtualBox_588](https://user-images.githubusercontent.com/1457929/84856520-3a08d980-b067-11ea-85ee-212e17043ba6.png)

**Comment by cpauya** [comment]
Yes, this build for the Windows installer doesn't work.  It still uses Python 3.4 based on the logs:

<img width="1128" alt="Screen Shot 2020-06-17 at 1 19 24 PM" src="https://user-images.githubusercontent.com/175580/84858225-57589a80-b09d-11ea-84a1-d776424778b7.png">

Thanks for the report @radinamatic - will look into this ASAP.

**Comment by cpauya** [comment]
Hi @radinamatic - I've tested the latest BuildKite artifact from the merged PR of @mrpau-richard  at https://buildkite.com/learningequality/kolibri-python-package/builds/1137 and it works now. 
<img width="739" alt="Screen Shot 2020-06-17 at 7 14 09 PM" src="https://user-images.githubusercontent.com/175580/84896395-7889ad00-b0d6-11ea-9175-d99c9eaf50a0.png">

**Comment by radinamatic** [comment]
All good on both W7 & 10, let's get this show on the road! :100: 

![Win7 (new start)  Running  - Oracle VM VirtualBox_598](https://user-images.githubusercontent.com/1457929/84968264-5d3e9200-b116-11ea-8a97-081687bc0f72.png)

![Win10 (ITA)  Running  - Oracle VM VirtualBox_599](https://user-images.githubusercontent.com/1457929/84968260-5b74ce80-b116-11ea-9c44-763173350626.png)


Fixed in learningequality/kolibri#7072
