### ISSUE TITLE
python 3.4 not automatically uninstalled after upgraded

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri-installer-windows#181]
### Observed behavior

I saw two python folder in `C:` drive (Python34 and python36), Which confuse to the users which one is currently running.
![image](https://user-images.githubusercontent.com/38421180/88008342-ef92d680-cac4-11ea-827a-7eeac23e2802.png)

And python 3.4 path still exists in the environment variables.
![image](https://user-images.githubusercontent.com/38421180/88008446-236dfc00-cac5-11ea-98a5-5ef2f5b0641a.png)

     
### Expected behavior

Maybe after upgrading, the python 3.4 will uninstall automatically and remove the python path in the environment variable.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

 * Kolibri version: upgrade from 0.13.3 to 0.14.0 beta 12
 * Operating system: Windows 10
 * Browser: N/A

**Comment by mrpau-julius** [comment]
Because of this issue, the port that I assign is not working (ex. 9999)
![image](https://user-images.githubusercontent.com/38421180/88018776-3a204d00-cadd-11ea-9ed9-1eb356403b25.png)

**Comment by mrpau-richard** [comment]
> I saw two python folder in C: drive (Python34 and python36), Which confuse to the users which one is currently running.
 
FYI - @mrpau-julius the Python version that Kolibri use to run will display at the Device info page.
![Screen Shot 2020-07-21 at 2 37 38 PM](https://user-images.githubusercontent.com/8663934/88021679-89f42800-cb60-11ea-8fa2-c7369d61a710.png)


> Because of this issue, the port that I assign is not working (ex. 9999)

I think you should close the command prompt after the environment variable is set, before running the Kolibri server. This was working on Windows 7
![Screen Shot 2020-07-21 at 2 46 43 PM](https://user-images.githubusercontent.com/8663934/88022077-2fa79700-cb61-11ea-84f2-061102075b8e.png)

**Comment by mrpau-julius** [comment]
Oh I see, nice! @mrpau-richard  do we have a way to delete python 3.4 folders automatically?

**Comment by indirectlylit** [comment]
We need to be a little careful: can we be sure that someone didn't install Python 3.4 on their own?

We don't want to delete things that the user may have put there intentionally.

**Comment by radinamatic** [comment]
Agreed, we should leave it to the user to uninstall programs/components should they need or desire to.

As long as Kolibri running or upgraded to version 0.14 is working as expected while using Python 3.6, I see no issues in leaving the Python 3.4 on the user' system.

**Comment by mrpau-julius** [comment]
Great! @indirectlylit @radinamatic, I will close this issue.
