### ISSUE TITLE
Correct erroneous assumption about port being the last line of the pid file

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-installer-windows#187]
Currently the code to get the active port from the Kolibri PID file assumes that it can keep reading the file until the file finishes:
https://github.com/learningequality/kolibri-installer-windows/blob/a55fb877b8c808eb302c6579424dc01afa8cdb99/src/gui-source/Kolibri/Kolibri.cpp#L76

However, recent updates have added additional lines to this PID file, meaning that it is now reading the wrong information.

Instead, we should update the code to only read the second line of the PID file to get the port.

Ideally, in future, we would use Kolibri's utils to determine this information, rather than introspecting the pid file - this will make it less brittle to future changes. But this fix will do for now.

**Comment by micahscopes** [comment]
Here's a gist verifying that the method of calling `getline` twice does indeed get the second line in a predictable way:

https://gist.github.com/micahscopes/348cdbed199588cdbf5a281291cc8b6a

I'm not sure what's going wrong at this point.

c.c. @jonboiser @rtibbles

**Comment by rtibbles** [comment]
Fixed in #188 and #192
