### ISSUE TITLE
Kolibri uninstaller is not showing in Windows 8 and 10

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#19]
@radinamatic commented in this [PR](https://github.com/learningequality/kolibri-installer-windows/pull/16#issuecomment-306823434) that Kolibri uninstall option is not showing in Windows 8 and 10. It's the same issue in KA Lite application.

**Comment by radinamatic** [comment]
10-4, merge away the #16 and it will be fixed!

**Comment by indirectlylit** [comment]
#16 is merged now - does that mean this is fixed?

**Comment by mrpau-richard** [comment]
@radinamatic I have these references saying, why the uninstall is not showing on Windows 8 and 10
```
You are probably a victim of such optimization.

Anyway, what you are trying to do is against Windows guidelines:

You should not use Start menu folders in Windows 8 and newer.
You should not add a shortcut to an uninstaller to the Start menu, on any version of Windows. The user should go to Control panel or Settings app to uninstall a program (that's also a possible explanation, why the shortcut is not shown).
```
Comments at [stackoverflow](https://stackoverflow.com/a/39371932)

```
You can uninstall an app directly from the Start menu by right-clicking its icon anywhere you see it and selecting Uninstall. This only works for the apps you’ve installed yourself and not those built into Windows 10.
```
[Uninstall apps fast](http://home.bt.com/tech-gadgets/computing/windows-10/secrets-windows-10-start-menu-11363997821398)
![screen shot 2017-12-01 at 3 05 47 pm](https://user-images.githubusercontent.com/8663934/33471893-65afc010-d6aa-11e7-982c-5ac1339f37ab.png)

I have these screenshots of some application also not showing its uninstall application at start menu.
![screen shot 2017-12-01 at 3 16 44 pm](https://user-images.githubusercontent.com/8663934/33471941-ab34e07a-d6aa-11e7-8bac-00dcdf964233.png)

![screen shot 2017-12-01 at 3 16 33 pm](https://user-images.githubusercontent.com/8663934/33471947-b43b1bda-d6aa-11e7-8890-a1f754b9671a.png)

**Comment by indirectlylit** [comment]
works for me!
