### ISSUE TITLE
Update the uninstall script

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#21]
We are already using InnoSetup (with GUI to uninstall Kolibri on Windows).  Let us update the uninstall script for these tasks:

- [x] Confirming from the user whether to remove (or not) the Kolibri data folder
- [x] Removing the environment variables
- [x] Show dialogs and texts based on the [Google Doc - Kolibri uninstall text](https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/)
- [ ] On error, show the `TaskDialogMsgBox()` with the traceback

Good to have (?)

- [ ] Internationalization support for the texts

References:
* https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/installer-source/KolibriSetupScript.iss
* https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/scripts/uninstall-kolibri.bat

Original Text:

~~Create uninstall script that will clean environment variables and installed files during uninstallation. It must have the same functionality at [kalite-remover.sh](https://github.com/learningequality/ka-lite-installers/blob/master/osx/ka-lite-remover.sh)~~

**Comment by indirectlylit** [comment]
targeted to 1.1.4

**Comment by rtibbles** [comment]
Would be good to have a nice UI alert to ask if the .kolibri folder should be deleted (but frame as - would you like to keep your data and content?)

**Comment by benjaoming** [comment]
@mrpau-richard says that there is already UI in the KA Lite removal script :)

**Comment by cpauya** [comment]
This is a miscommunication @benjaoming - we don't have a UI for this yet.  @mrpau-richard Please explain what you meant here.

**Comment by benjaoming** [comment]
Ah okay, you are probably right. Looking at the KA Lite uninstall script, it doesn't seem like it has any condition about removing or not removing user data...

https://github.com/learningequality/ka-lite-installers/blob/master/windows/scripts/uninstall-ka-lite-static.bat

**Comment by indirectlylit** [comment]
targeted to 1.3.2

**Comment by cpauya** [comment]
We already use InnoSetup (with GUI) to uninstall Kolibri in Windows: https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/installer-source/KolibriSetupScript.iss

Some tasks remain like:

1. Confirming from the user whether to remove (or not) the Kolibri data folder
1. Removing the environment variables
