### ISSUE TITLE
Make the pip installer hidden

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#22]
Python installer bundled into Kolibri, version 2.7.13 is actually not that bad, compared to previous versions. Not sure if we can couple that more tightly to Kolibri, since it's a separate program installation so it requires a separate confirmation from the user.

On another hand we do need to make the pip installs hidden so it neither requires a separate confirmation by the user, nor is visible to them. 

Keep in mind that user still needs feedback that something is happening during that stage, so it shouldn't be just the window with the green bar at 100% - it might need to be a new one with “Please wait while dependencies are installed…”.

![win7 start running - oracle vm virtualbox_405- no pip0](https://user-images.githubusercontent.com/1457929/28685542-74ab3a1e-7308-11e7-9db1-c19f8bbe4413.png)

![win7 start running - oracle vm virtualbox_405- no pip](https://user-images.githubusercontent.com/1457929/28684810-05c40bd2-7306-11e7-9b4a-4be26ddd6675.png)

**Comment by indirectlylit** [comment]
addresed!
