### ISSUE TITLE
Update copyright year to 2017

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-installer-windows#25]
currently shows 2015

<img width="498" alt="installation step 4 todo update 2017" src="https://user-images.githubusercontent.com/163966/28947330-3a54c1c6-787d-11e7-90eb-f7731fbf8857.png">

**Comment by radinamatic** [comment]
Apparently there is a [PR for that already](https://github.com/learningequality/kolibri-installer-windows/pull/1), albeit a bit stale...

**Comment by mrpau-richard** [comment]
Fixed in https://github.com/learningequality/kolibri-installer-windows/pull/1. Closing this
