### ISSUE TITLE
Maybe skip these informational steps

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-installer-windows#26]
Does the user need to know this?

<img width="479" alt="installation step 5 why do we need to know this" src="https://user-images.githubusercontent.com/163966/28947376-8fb25b9c-787d-11e7-80a1-8eae31b2751b.png">

I think it might be better to skip this informational message.

**Comment by radinamatic** [comment]
Apparently there is an [issue for that already](https://github.com/learningequality/kolibri-installer-windows/issues/22), too... :stuck_out_tongue:
