### ISSUE TITLE
Publisher: UNKNOWN

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-installer-windows#27]
On Win10 with default security options I get the following warning screens

<img width="536" alt="installation step 1" src="https://user-images.githubusercontent.com/163966/28947507-41724130-787e-11e7-9b6c-7ba3eb6afcd7.png">

<img width="464" alt="installation step 2" src="https://user-images.githubusercontent.com/163966/28947501-3c9a826c-787e-11e7-8537-a6f41e1bac58.png">

What do we have to do to "sign" the kolibri installer so these warning won't appear?
Does something like this popup in Win7? Win XP?

Then when Kolibri first starts:

<img width="526" alt="installation step 9" src="https://user-images.githubusercontent.com/163966/28947450-ef48bd44-787d-11e7-9e6c-204565d76034.png">

I guess there is no way to avoid this prompt, or could there be a workaround?

**Comment by radinamatic** [comment]
@ivanistheone Once we are done testing and ready to release the final installer, we do sign it prior to making it public, so the user is not "scared" but that first notification. :wink:

**Comment by radinamatic** [comment]
AFAIK, there is no way we can avoid the Win firewall alerting user, but that happens only at the first server start.

**Comment by indirectlylit** [comment]
closing - the signed version is a little less sketchy-looking
