### ISSUE TITLE
Update "Kolibri on the Web" links

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri-installer-windows#28]
<img width="314" alt="installation step 10 todo change link for kolibri on the web" src="https://user-images.githubusercontent.com/163966/28947634-edcfcd94-787e-11e7-9853-50e268514c59.png">

Currently takes you to https://learningequality.org/

Maybe it should point to https://community.learningequality.org/c/kolibri ?

**Comment by radinamatic** [comment]
Fair point @ivanistheone! 

Maybe keep that one and adding another for Community Forums...?

**Comment by mrpau-richard** [comment]
@radinamatic we can't add multiple Kolibri web links. either we replace it or retained it.

**Comment by mrpau-richard** [comment]
@radinamatic I read more in the Inno Setup documentation and yeah it's possible to add more kolibri web links.
