### ISSUE TITLE
internationalize installer and GUI

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#29]
For the public release, we'll need to internationalize both the installer program and the tray GUI program into about 8-10 languages. Let's discuss strategies here.

Requirements:
* All user-facing strings in both the installer and the tray application should be translated into our primary languages (TBD - but approx. 8-10 total)
* The visible language should be chosen based on the user's Windows locale settings

Nice-to-haves:
* Right to left language support
* Integration with our crowdin pipeline

----

@cpauya and co: would you mind proposing a few strategies here? If desired we can schedule a meeting to discuss in more detail.

cc @rtibbles @radinamatic

**Comment by mrpau-richard** [comment]
Hi @indirectlylit for the windows installer we can internationalize it. by creating [.isl](https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/inno-compiler/Default.isl) file and translate it into primary languages.

I'm still looking how we can internationalize the windows application tray GUI. 

I think we can do a meeting next week same day and time  we schedule our last meeting in `desktop tray applications and installers`

**Comment by indirectlylit** [comment]
Thanks sounds good!

Unfortunately I'll be out next week so a meeting won't be possible though.

**Comment by radinamatic** [comment]
@rtibbles has stepped in to join instead, and the meeting is on for next week! :wink:

**Comment by indirectlylit** [comment]
🎉
