### ISSUE TITLE
Issue with selecting 'no' to installing Python

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#30]
I tried selecting 'no' to the prompt to install Python. Saw two errors:

![image](https://user-images.githubusercontent.com/2367265/29099232-e67ec1fc-7c58-11e7-9e71-0078bea33327.png)

![image](https://user-images.githubusercontent.com/2367265/29099237-f3b809be-7c58-11e7-9fce-81e4c1b24641.png)

It would be better to just show a single message (not an error) that says "Kolibri cannot run without installing Python." and then quit after clicking OK.

----

Note - I was using the installer linked from [this comment](https://github.com/learningequality/kolibri-installer-windows/pull/24#issuecomment-320200547).

**Comment by mrpau-richard** [comment]
I will work on this @indirectlylit

**Comment by radinamatic** [comment]
@mrpau-richard 
The second error does need fixing, but my suggestion would be to change the message in order for the user to be able to come back and install Python:

![29099232-e67ec1fc-7c58-11e7-9e71-0078bea33327](https://user-images.githubusercontent.com/1457929/29131519-64b07a50-7d2d-11e7-905c-78e336d1badf.png)

`OK` button would restart the Python installer, and `Exit` would quit (without error, of course :wink:). This way user has the option to correct, and not need to re-run the `.exe` file to actually install Kolibri.

**Comment by indirectlylit** [comment]
Still seeing the second error:

![image](https://user-images.githubusercontent.com/2367265/31641819-16f555f2-b29c-11e7-836f-fbf5825f310f.png)

**Comment by mrpau-richard** [comment]
fixed in [#32](https://github.com/learningequality/kolibri-installer-windows/pull/32) closing this.

**Comment by indirectlylit** [comment]
@mrpau-richard I'm pretty the screenshot I posted was using the installer posted in #32

I'll test again!

**Comment by mrpau-richard** [comment]
Oh, sorry reopen this again.

**Comment by indirectlylit** [comment]
I just re-tested and cannot reproduce anymore, so I must have made a mistake
