### ISSUE TITLE
Could not find pip.exe

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#31]
I'm not sure what led to this, but here are the steps I went through:

* Loaded up an old VM that had an old version of Kolibri installed
* Uninstalled Kolibri
* Ran the new installer

I saw this message

![image](https://user-images.githubusercontent.com/2367265/29099289-5310c16c-7c59-11e7-91d5-d15e513b24fa.png)

Clicking 'OK' there let me to a file chooser where presumably I was supposed to find pip.exe.

I clicked cancel, and then the installer seemed to continue and claimed to have succeeded.

Two high-level issues:

* Any ideas how it got into a state where it couldn't find pip, and how this might be prevented?
* If for some reason something goes wrong, the whole installer should just fail (with a helpful message) and quit if possible. We shouldn't be asking the user to find and select a system executable.

----

Note - I was using the installer linked from [this comment](https://github.com/learningequality/kolibri-installer-windows/pull/24#issuecomment-320200547).

**Comment by mrpau-richard** [comment]
@indirectlylit the reason why we have that is when the installer can't find the `pip.exe` at path `\Python27\Scripts` it will show that option. To prevent this issue we must check if this path `\Python27\Scripts\pip.exe` exist  if not, We should ask the user to reinstall the python installer at the right path before the installation of Kolibri application.

I'll work on the issue when something goes wrong the installer should fail it's installation.

**Comment by mrpau-richard** [comment]
fixed in [#39](https://github.com/learningequality/kolibri-installer-windows/pull/39) closing this.
