### ISSUE TITLE
Kolibri installer throws an error

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#35]
reported by @jayoshih during the 0.6 hack session:

* https://storage.googleapis.com/le-downloads/kolibri%2Frelease%2F2448%2Freport.html
* Windows installer doesn't have Kolibri.exe file
* Try to install Kolibri on Windows. Running it returns an error

**Comment by mrpau-richard** [comment]
Hi @jayoshih I was successfully installed and ran the Kolibri installer from this [build](https://storage.googleapis.com/le-downloads/kolibri%2Frelease%2F2448%2Freport.html) in Windows 7 virtual box. 

@jayoshih may I know what operating system your using?

**Comment by radinamatic** [comment]
I've also tested several `0.6dev` builds and never run to that error. 
@jayoshih Did you try the latest 0.6 pre-release?

**Comment by indirectlylit** [comment]
closing as this doesn't seem to happen anymore
