### ISSUE TITLE
pop up tray menu on left or right click

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#40]
![image](https://user-images.githubusercontent.com/2367265/31642015-4d23a074-b29d-11e7-98b8-79e24b8714f1.png)

Currently, nothing happens if you left-click the tray icon; most other tray icons are interactive on left-click.

Would it be possible to pop up the menu on left _or_ right click?

**Comment by mrpau-richard** [comment]
@indirectlylit Yeah, It's possible to pop up the menu in the left click or right click.  I will work on this.
