### ISSUE TITLE
uninstaller buttons are not translated

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#42]
![image](https://user-images.githubusercontent.com/2367265/31678714-daec6be4-b323-11e7-86e6-33b209db5056.png)

![image](https://user-images.githubusercontent.com/2367265/31678872-4b7d0562-b324-11e7-9c79-1abfd226665f.png)

**Comment by mrpau-richard** [comment]
@indirectlylit I already explained this issue in @radinamatic [here](https://github.com/learningequality/kolibri-installer-windows/pull/36#issuecomment-334342661)

**Comment by indirectlylit** [comment]
thanks!
