### ISSUE TITLE
Split this repository into separate repos for Windows/Debian/Mac/PEX etc

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-windows#5]
Suggesting that we have:

kolibri-installer-windows
kolibri-installer-debian
kolibri-installer-mac
kolibri-installer-pex
kolibri-installer-android (rename kolibri-android-wrapper)

Several scenarios would indicate that we should split this repo IMO:

1. Different maintainers for each installer
1. A commit for installer X should not make the build server build all installers for X,Y,Z
1. Automated testing will be very prolonged in case you have a PR for Windows, and then tests are run for all the other installers
1. Issues for installer X will be prompting notifications for maintainer of installer Y
1. Branch strategy will be different depending on distribution *)
1. Experience from KA Lite **)

*) For instance on Debian, it's likely that we have just one single `debian/` source folder and never branch out to separate releases of Kolibri.

**) I'm opening this as an issue in order to have a discussion about it, but my opinion is largely based on ka-lite-installers

**Comment by indirectlylit** [comment]
It's a fair perspective - boils down in some ways to the [mono-repo debate](http://gregoryszorc.com/blog/2014/09/09/on-monolithic-repositories/). We've had [some discussion on Trello](https://trello.com/c/S426ftCK/626-make-official-le-repos-for-installers-or-migrate-to-kolibri-repo) previously on the topic.

While generally I'm in favor of mono-repos (and [recently suggested](https://github.com/learningequality/kolibri/pull/1218#discussion_r111435421) actually moving all the installer and server GUI code to the kolibri repo), I definitely agree that build/test times, contributor notification overload, and scoped code ownership are serious issues that need to be addressed as a repo grows in size and scope.

----

side note - in future conversations I'd also like to make a clear distinction between "installers" (the thing that is downloaded and run once to install kolibri) and "server UIs" (the code that e.g. on Windows or OSX provides an OS-native UI for starting/stopping the server.

**Comment by benjaoming** [comment]
@indirectlylit yes, I agree on the UI part. Actually, ka-lite-gtk is sitting in its own repo and isn't part of the ka-lite installer, but distributed as a separate (recommended, but optional!) dependency. I think the architecture should split up the UI from the Kolibri server, too. If we wanted bundled distributions, let them be so -- and not affect the architecture (versioning, repos etc).

**Comment by indirectlylit** [comment]
One other important distinction is modular architectures (decoupled components with clearly defined interfaces) vs modular repos (independent release cycles, versioning, and source control histories).

You can build a modular architecture in a mono-repo, or a tightly-coupled architecture with distributed-repos :)

**Comment by cpauya** [comment]
All very good points based on our experiences with KA-Lite installers @benjaoming.  And very good timing because this contains only the Windows installer codes for now.

The UI part indeed deserves another discussion @indirectlylit as it may be coded using a cross-platform toolkit such as QT, etc.

Let's get this installers repo split-up shall we? 😸

**Comment by mrpau-eduard** [comment]
If we separate the `kolibri-installer` repo, there are minimal impact since we are just starting the windows installer for now.
Below is the action items that will be implemented if we split the `kolibri-installer` repository into separate repos.

**Action Items**
1. Rename the `kolibri-installer` into kolibri-installer-windows.
2. Create a new repo for kolibri-installer-mac and kolibri-installer-debian.
3. Update [build_windows_installer.sh](https://github.com/learningequality/kolibri/blob/develop/.buildkite/build_windows_installer.sh#L15)  to point on the new installer repo.

It is safe to separate the `kolibri-installer` for now.

**Comment by benjaoming** [comment]
This is super, @indirectlylit could you give @mrpau-eduard 's action items a green light? I'm a big fan of separating out the immediate action items like @cpauya and @mrpau-eduard just did.. we can sort out release and workflows and other flows in due time, as long as we don't get stuck in big repos :)

**Comment by indirectlylit** [comment]
Just to be clear, are these repos for both the installers _and_ the runtime GUIs?

If so, we shouldn't call them "installer" repos - they should be named something like os-specific "wrapper" repos.

**Comment by indirectlylit** [comment]
> @indirectlylit could you give @mrpau-eduard 's action items a green light?

If you guys feel that there is minimal coupling between the various code bases, then yes this sounds fine to me.

**Comment by benjaoming** [comment]
Awesome, getting it done! Then there'll also be a new home for the debian installer:

https://github.com/learningequality/kolibri-installer-debian

**Comment by benjaoming** [comment]
We had another discussion about branching strategy for KA Lite installers. We'll remove the `develop` branch and have `master` + stable version branches. This is because `develop` and `master` have largely gone out of sync and made it quite confusing. De-facto it just made the `master` branch useless.

I'll bring it up at the next dev meeting I attend :)

**Comment by benjaoming** [comment]
> Just to be clear, are these repos for both the installers and the runtime GUIs?

Sorry, I didn't get back on this. No, I don't think there is consensus to keep them with the installers. I think when the effort happens, it should be sitting in its own repo, based on the widget toolkit. Installers can be responsible to bundle them and make them work on individual platforms.

For instance, I would be interested in doing `kolibri-controlpanel-gtk`, and then the one of the Debian binaries (a Debian source can build many binary packages from one source!) would either bundle it or add it as an optional dependency.

In the case of a GTK control panel, it *might* be feasible to write a Windows/Mac compatible version, but as of now, this is still to be decided, and QT is also a great option. Both can share the same UI designs.
