### ISSUE TITLE
Localization issue in the setup step

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#50]
Issue found while testing #49.

So the installer is started in English, and the Windows interface is set to be the default in English:

![win7 start running - oracle vm virtualbox_056](https://user-images.githubusercontent.com/1457929/33085367-cf9894fc-cee4-11e7-8825-c9040ec4edec.png)

The first few steps were shown in English, but then this one was displayed in Spanish:

![win7 start running - oracle vm virtualbox_059](https://user-images.githubusercontent.com/1457929/33085383-d5d9b1e8-cee4-11e7-9412-928ed5b7bbab.png)

The rest of the steps are displayed correctly in English. 

To see if I could replicate it, I rolled back the VM and restarted the installer with the Windows' user interface in French and selecting the French for the Kolibri installer. Everything displays correctly in French, apart from that sentence which is in English, but that's because it's our own string, not localized:

![win7 start running - oracle vm virtualbox_061](https://user-images.githubusercontent.com/1457929/33085843-358a2f22-cee6-11e7-9abd-8d89c0185e67.png)
 
If I switch to Spanish, everything is also displayed correctly:

![win7 start running - oracle vm virtualbox_062](https://user-images.githubusercontent.com/1457929/33086375-a8dea61e-cee7-11e7-8b52-37bed6f0ee66.png)

Please check why that sentence shows in Spanish when the default language is English?

**Comment by mrpau-richard** [comment]
@radinamatic that's my bad, I didn't clean the Inno setup compiler source, when I build that installer. I built a new one from the develop branch, and that issue you encountered can't be reproduced. You can download the installer [here](https://drive.google.com/open?id=1RW7FXrnXSFQUoJ7E6jwXoJIQn9Ndd-It) for the testing.
