### ISSUE TITLE
windows installer can take a very long time during final step

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#52]
Some recent reports from windows 10:

* 40 minutes inside a VM (@radinamatic)
* 10 minutes on a fast windows laptop (@alanchenz)

This is in the final stage when the green bar is at 100%, so it can look to the end-user like things are totally frozen unless they're savvy enough to check the task manager.

Furthermore, by this point the desktop 'Kolibri' icon has already been created and the user can try starting the server. If/when they do this, they get a 'server is already running' error.

**Comment by radinamatic** [comment]
Mine is 5 years old $200 laptop so that makes perfect sense... :joy: 

And we should definitely try to find a better solution to the fixed green bar (cc @mrpau-richard )

**Comment by radinamatic** [comment]
My testing with dev builds in a VM with 4GBs RAM on a fast desktop, never went over 5 minutes for the installation to finish. 

Maybe we can close this after #53 by @mrpau-richard is merged?
