### ISSUE TITLE
windows 10 notifications cause an audible, annoying 'ding'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#55]
We recently updated the installer to give periodic notifications while the server is starting up. This is helpful because otherwise the user has no way of knowing that an in-progress operation is happening:

![image](https://user-images.githubusercontent.com/2367265/33905743-74219f3c-df34-11e7-8abf-30f06a6075a4.png)

Unfortunately, it causes a 'ding' sound over and over. We should investigate alternative, less annoying ways of indicating this in-progress operation.

**Comment by mrpau-richard** [comment]
Fixed in #57, Closing this.
