### ISSUE TITLE
Rename the uninstaller file

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#58]
When user has all the notifications enabled, Windows asks for permission to let Kolibri uninstaller perform modifications on users computer, and since its name is `unins000.exe`, it might look suspicious. 

I suggest we rename it to `UninstallKolibri.exe` or similar, to avoid cautious users from disallowing the execution.

![win10 start running - oracle vm virtualbox_146](https://user-images.githubusercontent.com/1457929/34353263-6569db5a-ea27-11e7-89d6-6a60df088a19.png)

**Comment by mrpau-richard** [comment]
@radinamatic I have these references that renaming the `uninstall executable` is not recommended in Inno Setup.
https://stackoverflow.com/a/38278768
http://www.jrsoftware.org/iskb.php?uninstallername

**Comment by indirectlylit** [comment]
Sounds reasonable. It would be nice if they could be named e.g. `Uninstall-Kolibri-0.7.0.exe` to support the use-case described more cleanly, but sounds like that's not possible with Inno Setup
