### ISSUE TITLE
ensure port is correct if changed and other config options are respected

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#65]
Currently, port 8080 is hard-coded into the GUI in a few places. Instead, it should be dynamically driven either by an environment variable or by the status output of the Kolibri server

We recently introduced support for .ini file-based configuration: https://github.com/learningequality/kolibri/pull/3607

The windows launcher should respect .ini file config

**Comment by indirectlylit** [comment]
@mrpau-richard - updated this issue with new information regarding Kolibri config. I think we should look at making this work in the coming months

**Comment by indirectlylit** [comment]
targeted to 1.1.4

**Comment by benjaoming** [comment]
Hi @mrpau-richard - you asked me how to "generate" `options.ini` and I want to understand the question correctly:

Are you building a UI for users to configure the port differently from 8080? Or do you just want the port to be displayed in the UI and then you need to read the value?

The file is read and written to using Kolibri libraries, so it's best to invoke it this way.

But I have already previously mentioned that we need CLI for doing config read/writes, such that platform specific UIs don't invent too much of their own stuff :)

**Comment by indirectlylit** [comment]
> Are you building a UI for users to configure the port differently from 8080? Or do you just want the port to be displayed in the UI and then you need to read the value?

@benjaoming the purpose of this task is neither of these.

The goal is simpy that when an `options.ini` file with a configured port is provided, Kolibri runs on the correct port under windows.

**Comment by benjaoming** [comment]
Oh okay, but the installer doesn't specify its own port anywhere (environment nor command line switches) - does it?? So could it be that the entire `options.ini` is ignored?
