### ISSUE TITLE
Change to Python 3?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-windows#67]
I'm sure we've talked about this before: The built installer for Windows should not be based on Python 2.7

Here's an indirect consequence: https://github.com/learningequality/ka-lite-installers/pull/476

It seems that the issue is about using the .whl file built on Buildkite, but that file is now Python 3 compatible: https://github.com/learningequality/kolibri-installer-windows/pull/4

Could we target 0.10 for doing Python 3 on Windows?

**Comment by benjaoming** [comment]
@indirectlylit assigning you for guidance on when to get this done :)

**Comment by indirectlylit** [comment]
If in fact the blocker against using Python 3 is gone, then yes this seems like a good thing to tackle. @mrpau-richard would you mind taking this on in the next couple weeks?>
