### ISSUE TITLE
Upgrade to Python 3.6 and fix path assumptions

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-windows#70]
When moving back to Python 3.4.3, @mrpau-richard noted in #68:

> @benjaoming the reason why I didn't use the latest release, is because Python 3.5+ don't have msi Windows installer release.
> 
> When I try to use the exe installer, I have this C runtime issue when installing the Python path at the root path.
> 
> Python Windows release notes at the 3.5.0a2 and up.
> > Windows users: If installing Python 3.5.0a2 as a non-privileged user, you may need to escalate to administrator privileges to install an update to your C runtime libraries.

I think we should open an issue about this, the installer should be able to work with a Python environment installed anywhere.

**Comment by mrpau-richard** [comment]
We already upgraded to Python 3.6 on this [PR](https://github.com/learningequality/kolibri-installer-windows/pull/170), closing this
