### ISSUE TITLE
Can Python installer executables be removed from the repo?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-windows#71]
It's never a good idea to put binary code in an open source repository, for the following reasons:

1) It's binary, so not open source (even though its origins might be)
2) It's suspicious from a security perspective!
3) It makes the repository really big.

Currently, the footprint is >250 MB. It's actually the last reason that's my main grudge :)

1) [ ] Let's replace the Python installer with a convention (for instance an environment variable for the buildscript pointing to a URL + a checksum) and then have the Buildkite script (or whichever script is calling), define the path to the Python installer to-be-bundled (or none to skip!)

2) [ ] Completely wipe the old Python installer files from the history of the repo (re-writing the history)

**Comment by indirectlylit** [comment]
agreed - previously mentioned here https://github.com/learningequality/kolibri-installer-windows/pull/43#issuecomment-345487863

**Comment by indirectlylit** [comment]
one benefit seems to be that the exe is signed, so checking it in might help simplify the release process: https://github.com/learningequality/kolibri-installer-windows/pull/60

**Comment by mrpau-richard** [comment]
@benjaoming & @indirectlylit I also agreed to remove it. And create to script to download and bundled those installer files.

**Comment by benjaoming** [comment]
Sounds good @mrpau-richard -- have updated the issue description. I can help clean up the repo history once this is solved.

**Comment by indirectlylit** [comment]
if we need to keep any binary files vendored, we can use https://git-lfs.github.com/

**Comment by indirectlylit** [comment]
^-- ;-)

**Comment by benjaoming** [comment]
@indirectlylit if using LFS, do you know if the binary files and their history become unnecessary to download during `git clone`? The worst part of the problem is that in order to get the latest binary Python installer in the current repo, you also have to download the other 200 MB of commit history for said binary...

**Comment by benjaoming** [comment]
It seems actually that the website answers that :)

> Faster cloning and fetching
>
> Download less data. This means faster cloning and fetching from repositories that deal with large files.

**Comment by benjaoming** [comment]
Then the other issue is if it becomes an obstacle for build servers because they need extra components installed.

**Comment by mrpau-julius** [comment]
Hi @indirectlylit and @benjaoming, I'm working on this issue. Last week I installed the software that need in this task. Today I still studying the script code and soon I will post a comment here.

**Comment by benjaoming** [comment]
Sounds great @mrpau-julius, thanks for the update!

Not sure about the solution, but I would propose to add a step to the building of the installer where the Python installer gets downloaded, that should be sufficient.

The version of the installer should be specified such that it's easy to change it. Then we can discuss how often we should bump version of the Python installer that gets downloaded and bundled.

**Comment by cpauya** [comment]
I think we also need to remove the `inno-compiler` folder here: 
https://github.com/learningequality/kolibri-installer-windows/tree/develop/windows/inno-compiler

**Comment by benjaoming** [comment]
@cpauya - can the Docker / Wine-based building work if `inno-compiler` gets removed?

**Comment by cpauya** [comment]
Hi @benjaoming - we will include the above in our checking if it's possible.  Priority is to remove the Python installers in the repo of course. :)

**Comment by benjaoming** [comment]
The work on this issue has stalled quite a lot because we couldn't identify a way to download and verify a file in a reliable way on both Wine and/or Windows (8 and 10). The latest suggestion was to use a 4.1 MB helper tool to download Python... but I don't think we should put a binary file in the repo to get rid of another one :)

Instead, we will assume that the file is already downloaded and add a Makefile target which performs the current two steps:

1. Fetch the Python.exe and verify the download / skip if already downloaded
2. Call the setup builder

The Dockerfile in Kolibri can be adapted to call `make <target>`, rather than directly stating the build command.

**Comment by mrpau-richard** [comment]
Fixed in #92 closing this.
