### ISSUE TITLE
Kolibri might not be fully shut down during upgrade

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#78]
While investigating https://github.com/learningequality/kolibri/issues/3806, @rtibbles found evidence that the older instance of Kolibri was still running. This may have given rise to the issues seen there.

Let's investigate and make sure that Kolibri gets shut down cleanly and fully prior to upgrade

**Comment by indirectlylit** [comment]
We have another error that might be related to this issue - shown on upgrade but not a fresh install:

![image](https://user-images.githubusercontent.com/2367265/42653470-64cb1f58-85ca-11e8-9a62-0663ce10515b.png)

@mrpau-richard would you mind taking a look at this issue to see whether you can reproduce evidence that when upgrading, processes from the prior installation are not fully shut down?

**Comment by indirectlylit** [comment]
If shutting down is hard, we could add a check on upgrade, which looks for a running kolibri process and says to the user "Kolibri is still running. Please shut it down before upgrading"

**Comment by indirectlylit** [comment]
report: 

> this error can be fixed if you first stop the service kolibri.exe and then run the installer.
> doing that runs free of errors and successfully update the DB

**Comment by mrpau-richard** [comment]
I can't reproduce this issue, I tested these upgrades from 0.7.2, 0.8.0 0.9.2 to 0.10.0 and this issue never came out. I'm using Wind 7 and Win 10 to test this.

**Comment by radinamatic** [comment]
This was also not possible to reproduce during my share of integration testing on Windows VMs... 😕 

Scenarios specifically included the case of leaving the older version of Kolibri up and running, and then attempt the upgrade. Same as with @mrpau-richard, the upgrade concluded without issues, with the un-corrupted DB present, with all the users and past interactions visible upon start.

**Comment by indirectlylit** [comment]
I suppose there are two possibilities:

1. the hypothesis of incomplete shutdown is incorrect, and something else is causing the corrupted DBs and the errors seen in #76
2. incomplete shutdown does occur sometimes, and we haven't been able to reproduce the conditions

Since we don't know which one it is, we can continue investigating #76. However, it might be worth adding some additional checks during the installation process to be absolutely certain the all processes are killed, and if not show an error like "It looks like Kolibri is still running. Please terminate it using the Task Manager" or something similar?

**Comment by indirectlylit** [comment]
This issue is still happening in the field. Latest reported from the field: 

![image](https://user-images.githubusercontent.com/2367265/59607745-e70de680-90e1-11e9-90f7-42445fa6af78.png)

![image](https://user-images.githubusercontent.com/2367265/59607762-ed03c780-90e1-11e9-899b-8192f38f4d63.png)

![image](https://user-images.githubusercontent.com/2367265/59607777-f3923f00-90e1-11e9-9679-6dc10f4ffafa.png)

![image](https://user-images.githubusercontent.com/2367265/59607791-fab94d00-90e1-11e9-812b-1f6f83783d1e.png)

cc @mrpau-dev

**Comment by mrpau-richard** [comment]
> ![image](https://user-images.githubusercontent.com/2367265/59607745-e70de680-90e1-11e9-90f7-42445fa6af78.png)

I reported this issue [here](https://github.com/learningequality/kolibri/issues/5711) to gain more information about what the cause having this error and how to solve it.

> ![image](https://user-images.githubusercontent.com/2367265/59607762-ed03c780-90e1-11e9-899b-8192f38f4d63.png)

The fix of the screenshoot above is this PR #101 it's a duplication of this issue https://github.com/learningequality/kolibri-installer-windows/issues/94

> ![image](https://user-images.githubusercontent.com/2367265/59607777-f3923f00-90e1-11e9-9679-6dc10f4ffafa.png)

I reported this issue [here](https://github.com/learningequality/kolibri/issues/5712)

**Comment by indirectlylit** [comment]
thanks for the follow-up! I've asked @rtibbles and @kollivier why they believed that Kolibri sometimes doesn't shut down during upgrades, and the responses were:

* saw a couple screenshots from the installer that said `python.exe` couldn't be removed because it was in use
* weird post upgrade behaviors that looked like the old version was still running
* intuition

#101 will certainly help with error reporting and debugging, but it wouldn't address this issue directly. That said, we don't have any concrete evidence that it _is_ an issue. Therefore it's probably best to close this, and wait for future error messages to come in from the new-and-improved error reporting modal.
