### ISSUE TITLE
Improve the Python installer alerts

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#82]
Encountered during testing of #81.

After the (successful) upgrade from 0.9 to 0.10, I restarted the 0.10 installer again, and got the alert that the Python 3.4+ was needed for Kolibri to work. This alert is unnecessary and potentially confusing, since at that point the **_device already had both Python 2.7.13_** (from the 0.9 installation), **_and the Python 3.4.3_** (from the previous 0.10 installation).

![2018-09-09_4-44-56](https://user-images.githubusercontent.com/1457929/45312635-e6319e00-b52c-11e8-92cd-297f394576e9.png)

Furthermore, if the user is aware that they already have Python 3.4, and presses `No` at the above point, the next alert is even more confusing:

![2018-09-09_4-45-20](https://user-images.githubusercontent.com/1457929/45312757-34df3800-b52d-11e8-95d6-6ea48c5c8c51.png)

_"I know I have Python, but I have to install it again...?"_ 😕 

Truth be told, when the user resigns and accepts the _new_ Python installation by pressing `OK`, only then the "real" check seems to happen, and it is eventually skipped, since the Python is indeed there already... 

I suggest that the Kolibri installer should perform the check for the presence of Python silently, and only display these alerts **IF** there is none (or incorrect version) present on the device.

Thoughts @indirectlylit @mrpau-richard?

**Comment by indirectlylit** [comment]
> I suggest that the Kolibri installer should perform the check for the presence of Python silently, and only display these alerts **IF** there is none (or incorrect version) present on the device.

That sounds correct to me!

**Comment by mrpau-richard** [comment]
@radinamatic this issue only happened in Windows 10. I can't reproduce this in Windows 7. I'll do more research about this.

**Comment by radinamatic** [comment]
Confirmed that the issue is appearing only on Windows 10. 
On Windows 7, the Python installer alerts do not appear at all, and upon restart the installer immediately jumps to Kolibri installation settings.

![2018-09-19_3-59-56](https://user-images.githubusercontent.com/1457929/45726806-22b26900-bbc1-11e8-9a3b-8533bedea537.png)

Good hunting to you @mrpau-richard!
