### ISSUE TITLE
Make sure that 0.11 installer has all the recent changes

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#88]
PR #86 by @mrpau-richard has been tested and merged, but somehow did not make it into Kolibri 0.11.0b1:

![win7 start running - oracle vm virtualbox_049](https://user-images.githubusercontent.com/1457929/46993687-dfd8a800-d110-11e8-8a69-21b01b95c1a6.png)
(step with the checkbox for the shortcut is still present)

Let's make sure that the installer version is correct and that all the merged recent improvements get included into the final 0.11 release.

cc @indirectlylit

**Comment by mrpau-richard** [comment]
The changes of this [PR](https://github.com/learningequality/kolibri-installer-windows/pull/86) is already on the develop branch. I think the 0.11.0b1 Windows installer still using the old version tag and need to update it when building it at the BuildKite.

**Comment by mrpau-richard** [comment]
@indirectlylit I think we need to create another tag from the `kolibri-installer-windows` develop branch and update the `KOLIBRI_WINDOWS_INSTALLER_VERSION `environment variable [here](https://github.com/learningequality/kolibri/blob/c3068798664d73709dd2f9362e3c131b3f93b174/docker/env.list#L8).
