### ISSUE TITLE
gherkin stories for setting ports

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#89]
in #80 we added functionality to support setting ports in the options file

As a final step let's write some basic Gerkhin stories to document the possible expected behaviors and  add those to the Kolibri integration tests.

For example:

* given that I have or don't have an options.ini file with an alternate port set...
* given that I have or don't have the `KOLIBRI_HOME` environment variable set...

**Comment by mrpau-richard** [comment]
fixed in [#5703](https://github.com/learningequality/kolibri/pull/5703), closing this.
