### ISSUE TITLE
Create a separate pipeline on build kite for VF branded installers

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#9]
[This](https://files.slack.com/files-pri/T0KT5DC58-F52LCMQJE/download/kolibrisetup-0.3.1b3-instant-schools.exe) was supposed to be a Windows VF-branded installer, but the steps we used to make it such on Linux, did not work:
```
C:\Python27\Scripts>kolibri.exe plugin kolibri.plugins.user disable
C:\Python27\Scripts>kolibri.exe plugin kolibri_instant_schools_plugin enable
C:\Python27\Scripts>cmd /C "set DJANGO_SETTINGS_MODULE=kolibri_instant_schools_p
lugin.auth.phone_hashing_settings && kolibri.exe start"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\kolibri.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\kolibri\utils\cli.py", line 279, in main
    django.setup()
  File "C:\Python27\lib\site-packages\kolibri\dist\django\__init__.py", line 17,
 in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Python27\lib\site-packages\kolibri\dist\django\conf\__init__.py", lin
e 55, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\kolibri\dist\django\conf\__init__.py", lin
e 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\kolibri\dist\django\conf\__init__.py", lin
e 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named phone_hashing_settings
C:\Python27\Scripts>
```
Running the two last commands separately results in no command prompt error, but the server still gives 500 error:

![virtualbox_ie11 - win7_21_04_2017_19_51_50](https://cloud.githubusercontent.com/assets/1457929/25292220/815ffc1a-26d5-11e7-8973-5b996df782e6.png)

[Full `kolibri.log` here](https://learningequality.slack.com/files/radina/F53JS1NB1/kolibri.log), indicating the webpack build file is missing.

@rtibbles Suggests:

> Windows installer build process did not rebuild the frontend assets based on the vf plugin
> Because the frontend assets need to be rebuilt with the vf plugin in place, and that's not a normal part of the windows installer build process.
> ...pex for Linux is built differently
> But the windows installer takes the wheel file and then builds it off there
> But once the wheel file has been made, it's already too late for the instant schools rebranding to be in the build

**Comment by mrpau-eduard** [comment]
Hi @radinamatic will take a look on this issue and  create another pipeline on build kite for VF branded base on the suggestion of @rtibbles .

**Comment by radinamatic** [comment]
@mrpau-eduard Thanks, let me know if I can help in any way! 👍

**Comment by indirectlylit** [comment]
https://buildkite.com/learningequality/kolibri-vf
