### ISSUE TITLE
Insufficient error message when installer crashes

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-windows#94]
Hi @mrpau-dev 

I think it is quite critical if it's correct that the installation process crashes without any further guidance. Is there a way to log errors or capture exception information such that this error message can supply us with a more meaningful error message?

![image](https://user-images.githubusercontent.com/374612/55240909-3575bc80-523a-11e9-8310-dad8f15dbfb9.png)

**Comment by mrpau-julius** [comment]
This error means, the `C:\Python34\Scripts\pip.exe` cannot locate. please assign me here.

**Comment by benjaoming** [comment]
@mrpau-julius will you find a way to detect, log and display error messages in a more general way?

This issue is not just relevant for this single error, but for all future unknown errors :warning:

**Comment by cpauya** [comment]
Fixed in https://github.com/learningequality/kolibri-installer-windows/pull/108
